- hosts: all
  become: true
  gather_facts: yes
  # custom vars_files
  # vars_files:
  #   - group_vars/custom.yml
  roles:
    - common
    - security
    - app/cache
    - app/cicd
    - app/cms
    - app/database
    - app/git
    - app/monitor
    - app/storage
    - app/stream
  # run base on notified
  # handlers:
  #   - name: docker system prune
  #     service:
  #       name: apache2
  #       state: reloaded
