# TODO
# - GitHub Runner Install
# - GitHub Runner Uninstall
# - GitLab Runner Install
# - GitLab Runner Uninstall
# - Bitbucket Runner Install
# - Bitbucket Runner Uninstall
# - Jenkins Install
# - Jenkins Uninstall
