# TODO
# - MySQL Install
# - MySQL Uninstall
# - MariaDB Install
# - MariaDB Uninstall
# - PostgreSQL Install
# - PostgreSQL Uninstall
# - MongoDB Install
# - MongoDB Uninstall
# - Cassandra Install
# - Cassandra Uninstall