# TODO
# - Docker Engine Install
# - Docker Limit Logs Install
# - Docker System Prune Install
# - Docker Swarm Install
# - Docker Swarm Network Install
# - Docker Container Scale
# - Kong API Gateway
# - Portainer Management