---
- name: "create a directory if it does not exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: 
    - /home/{{ ansible_user }}/swarmgun/portainer
    - /home/{{ ansible_user }}/swarmgun/portainer-data
  tags: 
    - install-portainer

- name: "copy docker stack portainer"
  template:
    src: portainer.yaml.j2
    dest: /home/{{ ansible_user }}/swarmgun/portainer/portainer.yaml
  tags: 
    - install-portainer
    
- name: "run docker stack deploy portainer"
  community.docker.docker_stack:
    state: present
    name: portainer
    compose:
      - /home/{{ ansible_user }}/swarmgun/portainer/portainer.yaml
  tags:
    - install-portainer